name: Build and deploy mobile plugins

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy:
        environment:
           name: github-pages
           url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        permissions:
          contents: write
          pages: write

        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest

            - name: Install deps
              run: cd mobile && bun install

            - name: Build plugin(s)
              run: cd mobile && bun run build

            - name: Copy additional files
              run: |
                  cp README.md mobile/dist/README.md
                  printf -- "---\npermalink: /404.html\n---\n" > mobile/dist/404.md
                  printf -- "> **Note:** You accessed a link that returned a 404, probably by clicking one of the plugin links. You're supposed to copy the link address and add it into Vendetta.\n\n" >> mobile/dist/404.md
                  cat README.md >> mobile/dist/404.md

            - name: Setup Pages
              uses: actions/configure-pages@v5
            
            - name: Build with Jekyll
              uses: actions/jekyll-build-pages@v1
              with:
                source: ./mobile/dist
                destination: ./_site
                
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4